const nome = prompt('Digite seu nome completo:');
const tamanhoNome = nome.length
const segundaLetra = nome[1] // nome.charAt('1')
const primeiroA = (nome.indexOf('a'))
const ultimoA = (nome.lastIndexOf('a'))
const tresUltimas = (nome.slice(-3))
const nomeDividido = (nome.split(' '))
const nomeGrande = nome.toUpperCase()
const nomePequeno = nome.toLowerCase()
document.body.innerHTML += `Seu nome é: <strong>${nome}</strong><br />`;
document.body.innerHTML += `Seu nome tem <strong>${tamanhoNome}</strong> letras <br />`;
document.body.innerHTML += `A segunda letra do seu nome é: <strong>${segundaLetra}</strong> <br />`;
document.body.innerHTML += `Qual o primeiro índice da letra 'a' no seu nome? <strong>${primeiroA}</strong> <br />`;
document.body.innerHTML += `Qual o último índice da letra 'a' no seu nome? <strong>${ultimoA}</strong><br />`;
document.body.innerHTML += `As últimas 3 letras do seu nome são: <strong>${tresUltimas}</strong> <br />`;
document.body.innerHTML += `As palavras do seu nome são: <strong>${nomeDividido}</strong><br />`;
document.body.innerHTML += `Seu nome com letras maiúsculas: <strong>${nomeGrande}</strong><br />`;
document.body.innerHTML += `Seu nome com letras minúsculas: <strong>${nomePequeno}</strong><br />`;